/**
 * Fixture-based integration tests — real daemon-authored Automerge documents
 * loaded into WASM handles, synced through DirectTransport + SyncEngine.
 *
 * These fixtures are generated by `cargo test -p notebook-doc --test generate_fixtures`
 * and contain daemon-only mutations (outputs, execution counts) that can't be
 * done with WASM handles alone.
 *
 * The flow:
 * 1. Rust generates a NotebookDoc with daemon mutations → saves as doc.bin
 * 2. This test loads doc.bin into a WASM server handle via Handle.load()
 * 3. A fresh WASM client syncs via DirectTransport (real 2-party Automerge sync)
 * 4. Assertions verify daemon-authored state arrived correctly
 */

import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { VirtualAction, VirtualTimeScheduler } from "rxjs";
import { describe, expect, it } from "vitest";
import type { NotebookHandle } from "../../../apps/notebook/src/wasm/runtimed-wasm/runtimed_wasm";
import { DirectTransport, type ServerHandle } from "../src/direct-transport";
import type { SyncableHandle } from "../src/handle";
import { SyncEngine } from "../src/sync-engine";
import { initWasm } from "./wasm-harness";

// ── Fixture loading ──────────────────────────────────────────────────

const FIXTURES_DIR = resolve(__dirname, "fixtures");

interface ScenarioManifest {
  scenario: string;
  description: string;
  expected?: Record<string, unknown>;
  [key: string]: unknown;
}

function loadManifest(scenario: string): ScenarioManifest {
  const path = resolve(FIXTURES_DIR, scenario, "manifest.json");
  return JSON.parse(readFileSync(path, "utf-8"));
}

function loadDocBytes(scenario: string): Uint8Array {
  const path = resolve(FIXTURES_DIR, scenario, "doc.bin");
  return new Uint8Array(readFileSync(path));
}

function loadBroadcastFrames(scenario: string): Uint8Array[] {
  const dir = resolve(FIXTURES_DIR, scenario);
  const files = readdirSync(dir)
    .filter((f) => f.startsWith("broadcast_") && f.endsWith(".bin"))
    .sort();
  return files.map((f) => new Uint8Array(readFileSync(resolve(dir, f))));
}

// ── WASM server handle adapter ──────────────────────────────────────

class WasmServerHandle implements ServerHandle {
  readonly handle: NotebookHandle;

  constructor(handle: NotebookHandle) {
    this.handle = handle;
  }

  flush_local_changes(): Uint8Array | null {
    return this.handle.flush_local_changes() ?? null;
  }

  receive_sync_message(message: Uint8Array): boolean {
    return this.handle.receive_sync_message(message);
  }

  reset_sync_state(): void {
    this.handle.reset_sync_state();
  }
}

// ── Test setup ──────────────────────────────────────────────────────

async function setupFixtureSync(scenario: string) {
  const Handle = await initWasm();
  const docBytes = loadDocBytes(scenario);

  // Load the daemon-authored doc into a WASM server handle
  const server = Handle.load(docBytes);
  const serverAdapter = new WasmServerHandle(server);

  // Fresh client — knows nothing, will learn via sync
  const client = Handle.create_bootstrap(`fixture-client-${Date.now()}`);

  const scheduler = new VirtualTimeScheduler(VirtualAction, Infinity);
  const transport = new DirectTransport(serverAdapter);
  const engine = new SyncEngine({
    getHandle: () => client as unknown as SyncableHandle,
    transport,
    scheduler,
  });

  function advanceBy(ms: number): void {
    const target = scheduler.frame + ms;
    scheduler.maxFrames = target;
    scheduler.schedule(() => {}, ms);
    scheduler.flush();
  }

  async function startAndCompleteSync(): Promise<void> {
    engine.start();

    const syncComplete = new Promise<void>((resolve) => {
      const sub = engine.initialSyncComplete$.subscribe(() => {
        sub.unsubscribe();
        resolve();
      });
    });

    // Kick off the handshake
    engine.flush();

    // Run sync rounds until convergence
    for (let i = 0; i < 20; i++) {
      const pushed = transport.pushServerChanges();
      if (!pushed) break;
      await Promise.resolve();
    }

    await syncComplete;
  }

  return {
    server,
    client,
    engine,
    transport,
    scheduler,
    advanceBy,
    startAndCompleteSync,
    dispose() {
      engine.stop();
      server.free();
      client.free();
    },
  };
}

// ── Tests ────────────────────────────────────────────────────────────

describe("fixture-based integration: daemon-authored docs through WASM sync", () => {
  describe("output_streaming", () => {
    it("client receives cell with streamed outputs after sync", async () => {
      const manifest = loadManifest("output_streaming");
      const h = await setupFixtureSync("output_streaming");

      await h.startAndCompleteSync();

      // Client should have the cell with all outputs
      expect(h.client.cell_count()).toBe(1);
      expect(h.client.get_cell_source("cell-1")).toBe(
        manifest.expected!.source as string,
      );
      expect(h.client.get_cell_execution_count("cell-1")).toBe(
        manifest.expected!.execution_count as string,
      );

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(manifest.expected!.output_count as number);

      // Verify each output is valid JSON with correct structure
      for (const output of outputs) {
        const parsed = JSON.parse(output);
        expect(parsed.output_type).toBe("stream");
        expect(parsed.name).toBe("stdout");
      }

      h.dispose();
    });

    it("broadcasts arrive independently of sync frames", async () => {
      const broadcastFrames = loadBroadcastFrames("output_streaming");
      const h = await setupFixtureSync("output_streaming");

      await h.startAndCompleteSync();

      const broadcasts: unknown[] = [];
      const sub = h.engine.broadcasts$.subscribe((p) => broadcasts.push(p));

      // Deliver broadcast frames (these are separate from sync)
      for (const frame of broadcastFrames) {
        h.transport.deliver(Array.from(frame));
      }

      expect(broadcasts.length).toBe(3);
      for (const b of broadcasts) {
        const payload = b as Record<string, unknown>;
        expect(payload.type).toBe("Output");
        expect(payload.cell_id).toBe("cell-1");
      }

      sub.unsubscribe();

      h.dispose();
    });
  });

  describe("execution_with_error", () => {
    it("client receives error output after sync", async () => {
      const h = await setupFixtureSync("execution_with_error");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(1);
      expect(h.client.get_cell_source("cell-1")).toBe("1 / 0");
      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(1);

      const errorOutput = JSON.parse(outputs[0]);
      expect(errorOutput.output_type).toBe("error");
      expect(errorOutput.ename).toBe("ZeroDivisionError");
      expect(errorOutput.traceback.length).toBeGreaterThan(0);

      h.dispose();
    });
  });

  describe("re_execution", () => {
    it("client sees only second execution outputs after sync", async () => {
      const h = await setupFixtureSync("re_execution");

      await h.startAndCompleteSync();

      // After syncing the full document (which had execute → clear → re-execute),
      // client should see only the second execution's state
      expect(h.client.get_cell_execution_count("cell-1")).toBe("2");

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(1);

      const output = JSON.parse(outputs[0]);
      expect(output.output_type).toBe("execute_result");
      expect(output.data["text/plain"]).toBe("42");

      h.dispose();
    });
  });

  describe("multi_cell_execution", () => {
    it("client receives all cells with correct execution state", async () => {
      const h = await setupFixtureSync("multi_cell_execution");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(3);

      // cell-1: code, executed, no outputs
      expect(h.client.get_cell_type("cell-1")).toBe("code");
      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");
      expect(
        (h.client.get_cell_outputs("cell-1") as string[]).length,
      ).toBe(0);

      // cell-2: code, executed, one output
      expect(h.client.get_cell_type("cell-2")).toBe("code");
      expect(h.client.get_cell_execution_count("cell-2")).toBe("2");
      const cell2Outputs = h.client.get_cell_outputs("cell-2") as string[];
      expect(cell2Outputs.length).toBe(1);
      expect(JSON.parse(cell2Outputs[0]).text).toBe("42\n");

      // cell-3: markdown, no execution
      expect(h.client.get_cell_type("cell-3")).toBe("markdown");
      expect(h.client.get_cell_source("cell-3")).toBe("# Results");

      h.dispose();
    });
  });

  describe("display_data_output", () => {
    it("client receives manifest hash as output string", async () => {
      const h = await setupFixtureSync("display_data_output");

      await h.startAndCompleteSync();

      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(1);
      // Output should be the raw manifest hash (64 hex chars)
      expect(outputs[0]).toMatch(/^[a-f0-9]{64}$/);

      h.dispose();
    });
  });

  describe("changeset emission from daemon-authored docs", () => {
    it("emits changesets when incremental daemon changes arrive", async () => {
      const Handle = await initWasm();
      const docBytes = loadDocBytes("output_streaming");

      // Load the daemon doc, but we'll fork it to simulate incremental changes
      const server = Handle.load(docBytes);
      const serverAdapter = new WasmServerHandle(server);

      const client = Handle.create_bootstrap(
        `fixture-changeset-${Date.now()}`,
      );
      const scheduler = new VirtualTimeScheduler(VirtualAction, Infinity);
      const transport = new DirectTransport(serverAdapter);
      const engine = new SyncEngine({
        getHandle: () => client as unknown as SyncableHandle,
        transport,
        scheduler,
      });

      // Start and complete initial sync
      engine.start();
      const syncComplete = new Promise<void>((resolve) => {
        const sub = engine.initialSyncComplete$.subscribe(() => {
          sub.unsubscribe();
          resolve();
        });
      });
      engine.flush();
      for (let i = 0; i < 20; i++) {
        if (!transport.pushServerChanges()) break;
        await Promise.resolve();
      }
      await syncComplete;

      // Now subscribe to changesets and make an incremental server change
      const changesets: unknown[] = [];
      const sub = engine.cellChanges$.subscribe((cs) => changesets.push(cs));

      // Server-side mutation: update source (simulating daemon edit)
      server.update_source("cell-1", "print('changed')");
      transport.pushServerChanges();

      // Advance past coalescing window
      const target = scheduler.frame + 50;
      scheduler.maxFrames = target;
      scheduler.schedule(() => {}, 50);
      scheduler.flush();

      // Should have received at least one changeset
      expect(changesets.length).toBeGreaterThan(0);

      sub.unsubscribe();
      engine.stop();
      server.free();
      client.free();
    });
  });
});
